[package]
name = "theligi-data-access"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
uuid = { workspace = true, features = ["v4", "serde"] }
thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["sync"] }
tracing = { workspace = true }
async-trait = { workspace = true }
theligi-repository = { path = "../repository" }
theligi-cache = { path = "../cache" }
theligi-algorithm = { path = "../algorithm" }
theligi-authorization = { path = "../authorization" }
theligi-validation = { path = "../validation" }
daf-core = { path = "../../../theDAF/crates/daf-core", package = "daf-core" }
daf-application = { path = "../../../theDAF/crates/daf-application", package = "daf-application" }
daf-cache = { path = "../../../theDAF/crates/daf-cache", package = "daf-cache" }

[lib]
crate-type = ["rlib"]

[dev-dependencies]
theligi-content = { path = "../content" }
