[package]
name = "theligi-cache"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
uuid = { workspace = true, features = ["v4", "serde"] }
thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
dashmap = { workspace = true }
daf-core = { workspace = true }
daf-cache = { workspace = true }

[lib]
crate-type = ["rlib"]
