[package]
name = "theligi-runtime"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["rlib"]

[dependencies]
theligi-core = { path = "../core" }
theligi-context = { path = "../context" }
theligi-message = { path = "../message" }
theligi-query = { path = "../query" }
tokio = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tracing = { workspace = true }
anyhow = { workspace = true }
