[package]
name = "theligi-artifact"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["rlib"]

[dependencies]
tokio = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
async-trait = { workspace = true }
blake3 = { workspace = true }
