[package]
name = "theligi-telemetry"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["rlib"]

[dependencies]
tokio = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
themql-telemetry = { path = "../../../theMQL/crates/themql-telemetry", package = "themql-telemetry" }
