[package]
name = "theligi-core"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["rlib"]

[dependencies]
serde = { workspace = true, features = ["derive"] }
uuid = { workspace = true, features = ["v4", "serde"] }
thiserror = { workspace = true }
themql-core = { path = "../../../theMQL/crates/themql-core", package = "themql-core" }
daf-core = { path = "../../../theDAF/crates/daf-core", package = "daf-core" }
